apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeforge-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeforge
      version: blue
  template:
    metadata:
      labels:
        app: kubeforge
        version: blue
    spec:
      containers:
      - name: kubeforge-app
        image: nginx:alpine
        ports:
        - containerPort: 8080
