apiVersion: apps/v1
kind: Deployment
metadata:
  name: Kuberforge-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Kuberforge
      version: blue
  template:
    metadata:
      labels: 
        app: Kuberforge
        version: blue
    spec:
      containers:
      - name: kuberforge-app
        image: kuberforge-app:blue
        ports:
        - containerPort: 8080