apiversion: networking.k8s.io/v1
kind: ingress
metadata:
  name: kuberforge-ingress
  annotations:
    kubernetes.io/ingress.class: internet-facing
    alb.ingress.kubernetes.io/scheme: internet-facing
    alg.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
    paths:
    - path: /
    pathType: Prefix
    backend:
      service:
        name: kuberforge-service
        port:
          number: 80